from app.task_queue import get_broker


def get_all_job_ids() -> list[str]:
    """Get a list of all job ids generated by the broker

    :return: List of job ids
    """
    results_dict = get_broker().get_all_results()
    results: list[str] = []
    for category in results_dict.values():
        results.extend(category)
    return results
